# Generated by Django 2.1.3 on 2018-12-16 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recent',
            name='details',
            field=models.CharField(default='N/A', max_length=1000),
        ),
        migrations.AddField(
            model_name='recent',
            name='winner_average',
            field=models.CharField(default='N/A', max_length=10),
        ),
    ]
