# Generated by Django 2.1.3 on 2018-12-20 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20181216_1526'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recent1',
        ),
        migrations.RemoveField(
            model_name='recent',
            name='date',
        ),
        migrations.RemoveField(
            model_name='recent',
            name='name',
        ),
        migrations.RemoveField(
            model_name='recent',
            name='winner',
        ),
        migrations.RemoveField(
            model_name='recent',
            name='winner_average',
        ),
        migrations.AddField(
            model_name='recent',
            name='title',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='recent',
            name='details',
            field=models.CharField(default='', max_length=100000),
        ),
    ]
