# Generated by Django 2.1.3 on 2018-12-20 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20181220_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='recent',
            name='name',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
