# Generated by Django 2.1.3 on 2018-12-23 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='event_list',
            field=models.BooleanField(default=True),
        ),
    ]
