# Generated by Django 2.1.3 on 2018-12-23 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0002_competition_event_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competition',
            old_name='event_list',
            new_name='three_by_three',
        ),
    ]
