# Generated by Django 2.1.3 on 2018-12-24 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0003_auto_20181223_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='Clock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='competition',
            name='FMC',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='competition',
            name='Feet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='competition',
            name='Megaminx',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='competition',
            name='One_Handed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='competition',
            name='Pyraminx',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='competition',
            name='Skewb',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='competition',
            name='Square_1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='competition',
            name='five_blind',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='competition',
            name='five_by_five',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='competition',
            name='four_blind',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='competition',
            name='four_by_four',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='competition',
            name='multi_blind',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='competition',
            name='seven_by_seven',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='competition',
            name='six_by_six',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='competition',
            name='three_blind',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='competition',
            name='two_by_two',
            field=models.BooleanField(default=False),
        ),
    ]
