# Generated by Django 2.1.3 on 2018-12-11 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('complist', '0004_auto_20181211_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=50)),
                ('compcountry', models.CharField(default='DEFAULT VALUE', max_length=100)),
                ('compstate', models.CharField(default='DEFAULT VALUE', max_length=100)),
                ('compgender', models.CharField(default='DEFAULT VALUE', max_length=10)),
                ('compcomp', models.CharField(default='DEFAULT VALUE', max_length=100000)),
                ('compsolves', models.CharField(default='DEFAULT VALUE', max_length=1000000)),
            ],
        ),
        migrations.RemoveField(
            model_name='times',
            name='time',
        ),
        migrations.RemoveField(
            model_name='comp',
            name='compcomp',
        ),
        migrations.RemoveField(
            model_name='comp',
            name='compcountry',
        ),
        migrations.RemoveField(
            model_name='comp',
            name='compgender',
        ),
        migrations.RemoveField(
            model_name='comp',
            name='compsolves',
        ),
        migrations.RemoveField(
            model_name='comp',
            name='compstate',
        ),
        migrations.DeleteModel(
            name='Times',
        ),
        migrations.AddField(
            model_name='compdetails',
            name='time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complist.Comp'),
        ),
    ]
