# Generated by Django 2.1.3 on 2018-12-11 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('complist', '0005_auto_20181211_1420'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompDetails',
            new_name='Times',
        ),
        migrations.AlterField(
            model_name='times',
            name='time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complist.Comp'),
        ),
    ]
