# Generated by Django 2.1.3 on 2018-12-11 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('complist', '0006_auto_20181211_1426'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Times',
            new_name='CompDetails',
        ),
        migrations.AlterField(
            model_name='compdetails',
            name='time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complist.Comp'),
        ),
    ]
