# Generated by Django 2.1.3 on 2018-12-12 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('complist', '0010_auto_20181211_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='compdetails',
            name='BN',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='compdetails',
            name='GN',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='compdetails',
            name='ORN',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='compdetails',
            name='RRN',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='compdetails',
            name='SN',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='compdetails',
            name='SRN',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='compdetails',
            name='competitor_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complist.Comp'),
        ),
    ]
