# Generated by Django 2.1.3 on 2018-12-12 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('complist', '0012_auto_20181211_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comp',
            name='ORA',
        ),
        migrations.RemoveField(
            model_name='comp',
            name='ORS',
        ),
        migrations.AddField(
            model_name='compdetails',
            name='ORA',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='compdetails',
            name='ORS',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='compdetails',
            name='competitor_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complist.Comp'),
        ),
    ]
