# Generated by Django 2.1.3 on 2018-12-12 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('complist', '0013_auto_20181211_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compdetails',
            name='ORA',
            field=models.CharField(default='n/a', max_length=50),
        ),
        migrations.AlterField(
            model_name='compdetails',
            name='ORS',
            field=models.CharField(default='n/a', max_length=50),
        ),
        migrations.AlterField(
            model_name='compdetails',
            name='competitor_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complist.Comp'),
        ),
    ]
