# Generated by Django 2.1.3 on 2018-12-14 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('complist', '0014_auto_20181211_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompTimes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pb_single', models.CharField(default='', max_length=50)),
                ('pb_average', models.CharField(default='', max_length=50)),
                ('ORA', models.CharField(default='n/a', max_length=50)),
                ('ORS', models.CharField(default='n/a', max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='compdetails',
            name='ORA',
        ),
        migrations.RemoveField(
            model_name='compdetails',
            name='ORS',
        ),
        migrations.RemoveField(
            model_name='compdetails',
            name='pb_average',
        ),
        migrations.RemoveField(
            model_name='compdetails',
            name='pb_single',
        ),
        migrations.AlterField(
            model_name='compdetails',
            name='competitor_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complist.Comp'),
        ),
        migrations.AddField(
            model_name='comptimes',
            name='ename',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complist.CompDetails'),
        ),
    ]
